version: "3.8"
services:
  sql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3366:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: